services:
  - type: web
    name: job-portal-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
